using System.Security.Cryptography;
using KerckhoffsLabs.Security.Cryptography.Pkcs11.Algorithms;
using KerckhoffsLabs.Security.Cryptography.Pkcs11.Common;
using KerckhoffsLabs.Security.Cryptography.Pkcs11.Objects;
using KerckhoffsLabs.Security.Cryptography.Pkcs11.Tests.Support.Pkcs11Fakes;

#pragma warning disable CS0618 // DESPkcs11 is [Obsolete] — exercised intentionally.

namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Tests.Algorithms;

/// <summary>
/// DESPkcs11 over the in-process <c>ManagedSoftToken</c>. SoftHSM (FIPS build) refuses single-DES,
/// so its KAT skips — the managed token runs it. The DES key is generated by the BCL <see cref="DES"/>
/// (guaranteed non-weak) then imported.
/// </summary>
public sealed class DESPkcs11Tests_Managed
{
    [Fact]
    public void Cbc_Pkcs7_MatchesBclDes_OverManagedToken()
    {
        using var library = ManagedToken.NewLibrary();
        using var workspace = ManagedToken.OpenWorkspace(library);
        workspace.AllowInsecure = true; // single-DES is gated by the secure-defaults policy

        using var bcl = DES.Create();
        byte[] keyBytes = bcl.Key;

        using var tpl = ObjectTemplate.ForSecretKey(CKK.CKK_DES)
            .Label("des").Value(keyBytes).Encrypt().Decrypt().Build();
        using var key = workspace.ImportKey(tpl);
        using var des = new DESPkcs11(key);

        byte[] iv = RandomNumberGenerator.GetBytes(8);
        byte[] plaintext = RandomNumberGenerator.GetBytes(24);

        byte[] ct = des.EncryptCbc(plaintext, iv, PaddingMode.PKCS7);
        Assert.Equal(bcl.EncryptCbc(plaintext, iv, PaddingMode.PKCS7), ct);
        Assert.Equal(plaintext, des.DecryptCbc(ct, iv, PaddingMode.PKCS7));
    }

    [Fact]
    public void Ecb_MatchesBclDes_OverManagedToken()
    {
        using var library = ManagedToken.NewLibrary();
        using var workspace = ManagedToken.OpenWorkspace(library);
        workspace.AllowInsecure = true;

        using var bcl = DES.Create();
        byte[] keyBytes = bcl.Key;

        using var tpl = ObjectTemplate.ForSecretKey(CKK.CKK_DES)
            .Label("des-ecb").Value(keyBytes).Encrypt().Decrypt().Build();
        using var key = workspace.ImportKey(tpl);
        using var des = new DESPkcs11(key);

        byte[] plaintext = RandomNumberGenerator.GetBytes(16); // 2 blocks
        byte[] ct = des.EncryptEcb(plaintext, PaddingMode.None);
        Assert.Equal(bcl.EncryptEcb(plaintext, PaddingMode.None), ct);
        Assert.Equal(plaintext, des.DecryptEcb(ct, PaddingMode.None));
    }
}
