using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Generators;

/// <summary>
/// Collects every method marked <c>[Pkcs11Function]</c> and emits its function-pointer field
/// and — for <c>partial</c> methods — its body.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class DispatchGenerator : IIncrementalGenerator
{
    internal const string AttributeFullName =
        "KerckhoffsLabs.Security.Cryptography.Pkcs11.Native.Pkcs11FunctionAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var marked = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax,
            transform: static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(marked.Collect(), Emit);
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<IMethodSymbol> methods)
    {
        // Nothing declared yet: emitting empty partials would collide with the hand-written
        // members that still exist. Conversion happens task by task.
        if (methods.IsEmpty)
            return;

        // Each declaration is validated before it is trusted: TryBuild reports every diagnosable
        // problem (unmapped parameter type, misplaced annotation, WindowsLayout/packed-struct
        // disagreement, unrecognized version) and is skipped rather than emitted from, so a
        // declaration the emitter cannot handle is a build error instead of silently wrong —
        // or non-compiling — generated code.
        var built = new List<FunctionSpec>(methods.Length);
        foreach (IMethodSymbol m in methods)
        {
            if (DispatchModel.TryBuild(m, spc.ReportDiagnostic, out FunctionSpec f))
                built.Add(f);
        }
        var specs = built.OrderBy(f => f.Name).ToArray();

        var fields = new System.Text.StringBuilder();
        fields.AppendLine("// <auto-generated/> DispatchGenerator");
        fields.AppendLine("#nullable enable");
        fields.AppendLine();
        fields.AppendLine("namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Native;");
        fields.AppendLine();
        fields.AppendLine("internal sealed unsafe partial class FunctionPointers");
        fields.AppendLine("{");
        foreach (var f in specs)
            fields.Append(DispatchEmitter.Field(f));
        fields.AppendLine("}");
        spc.AddSource("FunctionPointers.g.cs", fields.ToString());

        var bodies = new System.Text.StringBuilder();
        bodies.AppendLine("// <auto-generated/> DispatchGenerator");
        bodies.AppendLine("#nullable enable");
        bodies.AppendLine();
        bodies.AppendLine("namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Native;");
        bodies.AppendLine();
        bodies.AppendLine("internal partial class Delegates");
        bodies.AppendLine("{");
        foreach (var f in specs)
        {
            if (!f.IsPartial) continue;
            bodies.Append("    public unsafe partial NativeCULong ").Append(f.Name).Append('(')
                  .Append(string.Join(", ", f.Params.Select(Declare))).AppendLine(")");
            bodies.AppendLine("    {");
            bodies.Append(DispatchEmitter.Body(f));
            bodies.AppendLine("    }");
            bodies.AppendLine();
        }
        bodies.AppendLine("}");
        spc.AddSource("Delegates.Dispatch.g.cs", bodies.ToString());

        // v3.0/v3.2 functions are optional: the token may not export them. C_GetFunctionList
        // (v2.40) is bootstrapped separately and has no Has/Bind pair — filtering to Version !=
        // "V240" is what excludes it (and every other v2.40 function) automatically.
        var v3Specs = specs.Where(f => f.Version != "V240").ToArray();
        var v240Specs = specs.Where(f => f.Version == "V240").ToArray();
        var v300Specs = specs.Where(f => f.Version == "V300").ToArray();
        var v320Specs = specs.Where(f => f.Version == "V320").ToArray();

        var binding = new System.Text.StringBuilder();
        binding.AppendLine("// <auto-generated/> DispatchGenerator");
        binding.AppendLine("#nullable enable");
        binding.AppendLine();
        binding.AppendLine("namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Native;");
        binding.AppendLine();
        binding.AppendLine("internal partial class Delegates");
        binding.AppendLine("{");

        foreach (var f in v3Specs)
            binding.Append(DispatchEmitter.HasProperty(f));
        binding.AppendLine();

        foreach (var f in v3Specs)
            binding.Append(DispatchEmitter.Binder(f));

        binding.AppendLine("    private unsafe void Initialize(CK_FUNCTION_LIST funcList)");
        binding.AppendLine("    {");
        foreach (var f in v240Specs)
            binding.Append(DispatchEmitter.InitializeAssignment(f));
        binding.AppendLine("    }");
        binding.AppendLine();

        binding.AppendLine("    private void BindV30FunctionList(CK_FUNCTION_LIST_3_0 v30)");
        binding.AppendLine("    {");
        foreach (var f in v300Specs)
            binding.Append(DispatchEmitter.TableBindCall(f, "v30"));
        binding.AppendLine("    }");
        binding.AppendLine();

        binding.AppendLine("    private void BindV32FunctionList(CK_FUNCTION_LIST_3_2 v32)");
        binding.AppendLine("    {");
        foreach (var f in v320Specs)
            binding.Append(DispatchEmitter.TableBindCall(f, "v32"));
        binding.AppendLine("    }");
        binding.AppendLine();

        binding.AppendLine("    private void BindV3SymbolsFromResolver(Func<string, IntPtr> resolveExport)");
        binding.AppendLine("    {");
        foreach (var f in v3Specs)
            binding.Append(DispatchEmitter.ResolverBindCall(f));
        binding.AppendLine("    }");

        binding.AppendLine("}");
        spc.AddSource("Delegates.Binding.g.cs", binding.ToString());
    }

    private static string Declare(ParamSpec p) => p.RefKind switch
    {
        RefKind.Ref => $"ref {p.ManagedType} {p.Name}",
        RefKind.Out => $"out {p.ManagedType} {p.Name}",
        _ => $"{p.ManagedType} {p.Name}",
    };
}
