using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class PackedStructsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName =
        "KerckhoffsLabs.Security.Cryptography.Pkcs11.Native.PackedForPkcs11Attribute";

    // Repeated code-emission fragments, factored out to a single definition (S1192).
    private const string OpenBrace = "    {";                     // member-body / object-initializer open
    private const string CloseBrace = "    }";                    // member-body close
    private const string OpenBraceNested = "        {";           // dispatch if-block open
    private const string CloseBraceNested = "        }";          // dispatch if-block close
    private const string FieldIndent = "        ";               // 8-space indent for field assignments
    private const string IfTypeEquals = "        if (t == typeof("; // non-generic type-equality test

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var marked = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is StructDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(marked.Collect(), Emit);
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<INamedTypeSymbol> syms)
    {
        // Nothing to dispatch: this compilation declares no [PackedForPkcs11] structs. Emitting an
        // empty PackedDispatch anyway would collide (CS0436) with the real one in any assembly that
        // references the library and also loads this analyzer — e.g. the test project, which runs
        // the shipped analyzers against itself.
        if (syms.IsEmpty)
            return;

        // Map each marked type's fully-qualified name to its Windows-sibling type name
        // ("CK_INFO" -> "CK_INFO_Windows"). Used to substitute field types when emitting.
        var packedNames = syms
            .ToDictionary(s => s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                          s => s.Name + "_Windows");

        foreach (var sym in syms)
            spc.AddSource($"{sym.Name}_Windows.g.cs", SourceText.From(Render(sym, packedNames), Encoding.UTF8));

        spc.AddSource("PackedDispatch.g.cs", SourceText.From(RenderDispatch(syms), Encoding.UTF8));
    }

    private static string Render(INamedTypeSymbol sym, IReadOnlyDictionary<string, string> packedNames)
    {
        var ns = sym.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> PackedStructsGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("[StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Unicode)]");
        sb.Append("internal partial struct ").Append(sym.Name).AppendLine("_Windows");
        sb.AppendLine("{");

        var fields = sym.GetMembers().OfType<IFieldSymbol>()
            .Where(f => !f.IsStatic && !f.IsConst).ToArray();

        foreach (var f in fields)
            EmitField(sb, f, packedNames);

        sb.AppendLine();
        EmitFromUnified(sb, sym, fields, packedNames);
        sb.AppendLine();
        EmitToUnified(sb, sym, fields, packedNames);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitField(StringBuilder sb, IFieldSymbol f,
                                   IReadOnlyDictionary<string, string> packedNames)
    {
        // Forward any [MarshalAs] / [In] / [Out] attributes verbatim.
        foreach (var a in f.GetAttributes())
        {
            var ac = a.AttributeClass;
            if (ac is null) continue;
            // Skip [PackedForPkcs11] (it's on the type, not fields, but defensive).
            if (ac.ToDisplayString() == AttributeFullName) continue;
            sb.Append("    [").Append(a).AppendLine("]");
        }
        var typeName = SubstituteFieldType(f.Type, packedNames);
        sb.Append("    public ").Append(typeName).Append(' ').Append(f.Name).AppendLine(";");
    }

    private static string SubstituteFieldType(ITypeSymbol t, IReadOnlyDictionary<string, string> packedNames)
    {
        // Walk arrays / pointers. No native struct currently declares an array field — inline
        // fixed-size buffers use [InlineArray] value types — but the branch is kept for safety.
        if (t is IArrayTypeSymbol arr)
            return SubstituteFieldType(arr.ElementType, packedNames) + "[]";

        var key = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (packedNames.TryGetValue(key, out var winName))
        {
            // Use the simple name when the windows sibling is in the same namespace
            // (every marked struct lives in Native/ or Native/RawMechanismParams/).
            return winName;
        }
        return t.ToDisplayString();
    }

    private static void EmitFromUnified(StringBuilder sb, INamedTypeSymbol sym,
                                          IFieldSymbol[] fields,
                                          IReadOnlyDictionary<string, string> packedNames)
    {
        sb.Append("    public static ").Append(sym.Name).Append("_Windows FromUnified(in ").Append(sym.Name).AppendLine(" src) => new()");
        sb.AppendLine(OpenBrace);
        foreach (var f in fields)
        {
            var key = f.Type is IArrayTypeSymbol arr
                ? arr.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (packedNames.TryGetValue(key, out var winName))
            {
                if (f.Type is IArrayTypeSymbol)
                {
                    // Element-wise conversion for arrays of packed types.
                    sb.Append(FieldIndent).Append(f.Name).Append(" = src.").Append(f.Name)
                      .Append(" is null ? null! : System.Array.ConvertAll(src.").Append(f.Name)
                      .Append(", ").Append(winName).AppendLine(".FromUnified),");
                }
                else
                {
                    sb.Append(FieldIndent).Append(f.Name).Append(" = ").Append(winName)
                      .Append(".FromUnified(in src.").Append(f.Name).AppendLine("),");
                }
            }
            else
            {
                sb.Append(FieldIndent).Append(f.Name).Append(" = src.").Append(f.Name).AppendLine(",");
            }
        }
        sb.AppendLine("    };");
    }

    private static void EmitToUnified(StringBuilder sb, INamedTypeSymbol sym,
                                        IFieldSymbol[] fields,
                                        IReadOnlyDictionary<string, string> packedNames)
    {
        sb.Append("    public ").Append(sym.Name).AppendLine(" ToUnified() => new()");
        sb.AppendLine(OpenBrace);
        foreach (var f in fields)
        {
            var key = f.Type is IArrayTypeSymbol arr
                ? arr.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (packedNames.TryGetValue(key, out _))
            {
                if (f.Type is IArrayTypeSymbol)
                {
                    sb.Append(FieldIndent).Append(f.Name).Append(" = this.").Append(f.Name)
                      .Append(" is null ? null! : System.Array.ConvertAll(this.").Append(f.Name)
                      .Append(", static w => w.ToUnified()),");
                    sb.AppendLine();
                }
                else
                {
                    sb.Append(FieldIndent).Append(f.Name).Append(" = this.").Append(f.Name).AppendLine(".ToUnified(),");
                }
            }
            else
            {
                sb.Append(FieldIndent).Append(f.Name).Append(" = this.").Append(f.Name).AppendLine(",");
            }
        }
        sb.AppendLine("    };");
    }

    // ---- PackedDispatch emission ----

    private static string RenderDispatch(ImmutableArray<INamedTypeSymbol> syms)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> PackedStructsGenerator dispatch");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Native;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generator-emitted dispatch table for every <c>[PackedForPkcs11]</c>-marked struct.");
        sb.AppendLine("/// The <c>typeof(T) == typeof(...)</c> chains are JIT/AOT-folded per generic instantiation,");
        sb.AppendLine("/// so callers pay one direct call — no reflection, no <c>[RequiresDynamicCode]</c>.");
        sb.AppendLine("/// Non-generic overloads use <c>t == typeof(...)</c> type-equality and <c>is T</c> patterns");
        sb.AppendLine("/// — also AOT-safe because no dynamic code is generated.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class PackedDispatch");
        sb.AppendLine("{");

        EmitGenericSizeOfWindows(sb, syms);
        sb.AppendLine();
        EmitGenericWriteWindows(sb, syms);
        sb.AppendLine();
        EmitGenericReadWindows(sb, syms);
        sb.AppendLine();
        EmitNonGenericSizeOfWindows(sb, syms);
        sb.AppendLine();
        EmitNonGenericSizeOfUnified(sb, syms);
        sb.AppendLine();
        EmitNonGenericWriteWindows(sb, syms);
        sb.AppendLine();
        EmitNonGenericWriteUnified(sb, syms);
        sb.AppendLine();
        EmitNonGenericReadWindows(sb, syms);
        sb.AppendLine();
        EmitNonGenericReadUnified(sb, syms);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ---- Helpers ----

    /// <summary>Returns the fully-qualified unified type name, e.g. "global::...Native.CK_INFO".</summary>
    private static string FqUnified(INamedTypeSymbol sym) =>
        sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    /// <summary>Returns the fully-qualified Windows sibling name, e.g. "global::...Native.CK_INFO_Windows".</summary>
    private static string FqWindows(INamedTypeSymbol sym)
    {
        var ns = sym.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return ns + "." + sym.Name + "_Windows";
    }

    // ---- Generic dispatch methods ----

    private static void EmitGenericSizeOfWindows(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Returns the unmanaged size of the Windows-packed sibling of <typeparamref name=\"T\"/>.</summary>");
        sb.AppendLine("    public static int SizeOfWindows<T>() where T : unmanaged");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append("        if (typeof(T) == typeof(").Append(FqUnified(sym)).Append(")) return Unsafe.SizeOf<")
              .Append(FqWindows(sym)).AppendLine(">();");
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.SizeOfWindows<T>: type {typeof(T)} has no Windows sibling.\");");
        sb.AppendLine(CloseBrace);
    }

    private static void EmitGenericWriteWindows(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Converts <paramref name=\"src\"/> to its Windows-packed sibling and writes it to <paramref name=\"memory\"/>.</summary>");
        sb.AppendLine("    public static unsafe void WriteWindows<T>(System.IntPtr memory, in T src) where T : unmanaged");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append("        if (typeof(T) == typeof(").Append(FqUnified(sym)).AppendLine("))");
            sb.AppendLine(OpenBraceNested);
            sb.Append("            var win = ").Append(FqWindows(sym))
              .Append(".FromUnified(in Unsafe.As<T, ").Append(FqUnified(sym))
              .AppendLine(">(ref Unsafe.AsRef(in src)));");
            sb.Append("            Unsafe.WriteUnaligned((void*)memory, win);");
            sb.AppendLine();
            sb.AppendLine("            return;");
            sb.AppendLine(CloseBraceNested);
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.WriteWindows<T>: type {typeof(T)} has no Windows sibling.\");");
        sb.AppendLine(CloseBrace);
    }

    private static void EmitGenericReadWindows(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Reads the Windows-packed sibling from <paramref name=\"memory\"/> and converts it to the unified <typeparamref name=\"T\"/>.</summary>");
        sb.AppendLine("    public static unsafe T ReadWindows<T>(System.IntPtr memory) where T : unmanaged");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append("        if (typeof(T) == typeof(").Append(FqUnified(sym)).AppendLine("))");
            sb.AppendLine(OpenBraceNested);
            sb.Append("            var win = Unsafe.ReadUnaligned<").Append(FqWindows(sym)).AppendLine(">((void*)memory);");
            sb.AppendLine("            var u = win.ToUnified();");
            sb.Append("            return Unsafe.As<").Append(FqUnified(sym)).AppendLine(", T>(ref u);");
            sb.AppendLine(CloseBraceNested);
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.ReadWindows<T>: type {typeof(T)} has no Windows sibling.\");");
        sb.AppendLine(CloseBrace);
    }

    // ---- Non-generic dispatch methods (for object-based callers in UnmanagedMemory) ----

    private static void EmitNonGenericSizeOfWindows(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Returns the unmanaged size of the Windows-packed sibling of <paramref name=\"t\"/>.</summary>");
        sb.AppendLine("    public static int SizeOfWindows(System.Type t)");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append(IfTypeEquals).Append(FqUnified(sym)).Append(")) return Unsafe.SizeOf<")
              .Append(FqWindows(sym)).AppendLine(">();");
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.SizeOfWindows(Type): type {t} has no Windows sibling.\");");
        sb.AppendLine(CloseBrace);
    }

    private static void EmitNonGenericSizeOfUnified(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Returns the unmanaged size of the unified (non-packed) type <paramref name=\"t\"/>.</summary>");
        sb.AppendLine("    public static int SizeOfUnified(System.Type t)");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append(IfTypeEquals).Append(FqUnified(sym)).Append(")) return Unsafe.SizeOf<")
              .Append(FqUnified(sym)).AppendLine(">();");
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.SizeOfUnified(Type): type {t} is not a known [PackedForPkcs11] type.\");");
        sb.AppendLine(CloseBrace);
    }

    private static void EmitNonGenericWriteWindows(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Converts the boxed packed struct <paramref name=\"src\"/> to its Windows sibling and writes it to <paramref name=\"memory\"/>.</summary>");
        sb.AppendLine("    public static unsafe void WriteWindows(System.IntPtr memory, object src)");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append("        if (src is ").Append(FqUnified(sym)).AppendLine(" v" + sym.Name + ")");
            sb.AppendLine(OpenBraceNested);
            sb.Append("            var win = ").Append(FqWindows(sym)).Append(".FromUnified(in v").Append(sym.Name).AppendLine(");");
            sb.Append("            Unsafe.WriteUnaligned((void*)memory, win);");
            sb.AppendLine();
            sb.AppendLine("            return;");
            sb.AppendLine(CloseBraceNested);
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.WriteWindows(object): type {src?.GetType()} has no Windows sibling.\");");
        sb.AppendLine(CloseBrace);
    }

    private static void EmitNonGenericWriteUnified(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Writes the boxed packed struct <paramref name=\"src\"/> (unified layout) to <paramref name=\"memory\"/>.</summary>");
        sb.AppendLine("    public static unsafe void WriteUnified(System.IntPtr memory, object src)");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append("        if (src is ").Append(FqUnified(sym)).AppendLine(" v" + sym.Name + ")");
            sb.AppendLine(OpenBraceNested);
            sb.Append("            Unsafe.WriteUnaligned((void*)memory, v").Append(sym.Name).AppendLine(");");
            sb.AppendLine("            return;");
            sb.AppendLine(CloseBraceNested);
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.WriteUnified(object): type {src?.GetType()} is not a known [PackedForPkcs11] type.\");");
        sb.AppendLine(CloseBrace);
    }

    private static void EmitNonGenericReadWindows(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Reads the Windows-packed sibling from <paramref name=\"memory\"/> and returns the boxed unified struct.</summary>");
        sb.AppendLine("    public static unsafe object ReadWindows(System.IntPtr memory, System.Type t)");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append(IfTypeEquals).Append(FqUnified(sym)).AppendLine("))");
            sb.AppendLine(OpenBraceNested);
            sb.Append("            var win = Unsafe.ReadUnaligned<").Append(FqWindows(sym)).AppendLine(">((void*)memory);");
            sb.AppendLine("            return win.ToUnified();");
            sb.AppendLine(CloseBraceNested);
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.ReadWindows(Type): type {t} has no Windows sibling.\");");
        sb.AppendLine(CloseBrace);
    }

    private static void EmitNonGenericReadUnified(StringBuilder sb, ImmutableArray<INamedTypeSymbol> syms)
    {
        sb.AppendLine("    /// <summary>Reads the unified (non-packed) struct from <paramref name=\"memory\"/> and returns it boxed.</summary>");
        sb.AppendLine("    public static unsafe object ReadUnified(System.IntPtr memory, System.Type t)");
        sb.AppendLine(OpenBrace);
        foreach (var sym in syms)
        {
            sb.Append(IfTypeEquals).Append(FqUnified(sym)).AppendLine("))");
            sb.AppendLine(OpenBraceNested);
            sb.Append("            return Unsafe.ReadUnaligned<").Append(FqUnified(sym)).AppendLine(">((void*)memory);");
            sb.AppendLine(CloseBraceNested);
        }
        sb.AppendLine("        throw new System.InvalidOperationException($\"PackedDispatch.ReadUnified(Type): type {t} is not a known [PackedForPkcs11] type.\");");
        sb.AppendLine(CloseBrace);
    }
}
