using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.SourceGen;

[Generator(LanguageNames.CSharp)]
public sealed class PackedStructsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName =
        "KerckhoffsLabs.Security.Cryptography.Pkcs11.Native.PackedForPkcs11Attribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var marked = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is StructDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(marked.Collect(), Emit);
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<INamedTypeSymbol> syms)
    {
        // Map each marked type's fully-qualified name to its Windows-sibling type name
        // ("CK_INFO" -> "CK_INFO_Windows"). Used to substitute field types when emitting.
        var packedNames = syms
            .ToDictionary(s => s.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                          s => s.Name + "_Windows");

        foreach (var sym in syms)
            spc.AddSource($"{sym.Name}_Windows.g.cs", SourceText.From(Render(sym, packedNames), Encoding.UTF8));
    }

    private static string Render(INamedTypeSymbol sym, IReadOnlyDictionary<string, string> packedNames)
    {
        var ns = sym.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> PackedStructsGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("[StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Unicode)]");
        sb.Append("internal partial struct ").Append(sym.Name).AppendLine("_Windows");
        sb.AppendLine("{");

        var fields = sym.GetMembers().OfType<IFieldSymbol>()
            .Where(f => !f.IsStatic && !f.IsConst).ToArray();

        foreach (var f in fields)
            EmitField(sb, f, packedNames);

        sb.AppendLine();
        EmitFromUnified(sb, sym, fields, packedNames);
        sb.AppendLine();
        EmitToUnified(sb, sym, fields, packedNames);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitField(StringBuilder sb, IFieldSymbol f,
                                   IReadOnlyDictionary<string, string> packedNames)
    {
        // Forward any [MarshalAs] / [In] / [Out] attributes verbatim.
        foreach (var a in f.GetAttributes())
        {
            var ac = a.AttributeClass;
            if (ac is null) continue;
            // Skip [PackedForPkcs11] (it's on the type, not fields, but defensive).
            if (ac.ToDisplayString() == AttributeFullName) continue;
            sb.Append("    [").Append(a.ToString()).AppendLine("]");
        }
        var typeName = SubstituteFieldType(f.Type, packedNames);
        sb.Append("    public ").Append(typeName).Append(' ').Append(f.Name).AppendLine(";");
    }

    private static string SubstituteFieldType(ITypeSymbol t, IReadOnlyDictionary<string, string> packedNames)
    {
        // Walk arrays / pointers — for now only handle T and T[] (ByValArray flattens to inline).
        if (t is IArrayTypeSymbol arr)
            return SubstituteFieldType(arr.ElementType, packedNames) + "[]";

        var key = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (packedNames.TryGetValue(key, out var winName))
        {
            // Use the simple name when the windows sibling is in the same namespace
            // (every marked struct lives in Native/ or Native/RawMechanismParams/).
            return winName;
        }
        return t.ToDisplayString();
    }

    private static void EmitFromUnified(StringBuilder sb, INamedTypeSymbol sym,
                                          IFieldSymbol[] fields,
                                          IReadOnlyDictionary<string, string> packedNames)
    {
        sb.Append("    public static ").Append(sym.Name).Append("_Windows FromUnified(in ").Append(sym.Name).AppendLine(" src) => new()");
        sb.AppendLine("    {");
        foreach (var f in fields)
        {
            var key = f.Type is IArrayTypeSymbol arr
                ? arr.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (packedNames.TryGetValue(key, out var winName))
            {
                if (f.Type is IArrayTypeSymbol)
                {
                    // Element-wise conversion for arrays of packed types.
                    sb.Append("        ").Append(f.Name).Append(" = src.").Append(f.Name)
                      .Append(" is null ? null! : System.Array.ConvertAll(src.").Append(f.Name)
                      .Append(", ").Append(winName).AppendLine(".FromUnified),");
                }
                else
                {
                    sb.Append("        ").Append(f.Name).Append(" = ").Append(winName)
                      .Append(".FromUnified(in src.").Append(f.Name).AppendLine("),");
                }
            }
            else
            {
                sb.Append("        ").Append(f.Name).Append(" = src.").Append(f.Name).AppendLine(",");
            }
        }
        sb.AppendLine("    };");
    }

    private static void EmitToUnified(StringBuilder sb, INamedTypeSymbol sym,
                                        IFieldSymbol[] fields,
                                        IReadOnlyDictionary<string, string> packedNames)
    {
        sb.Append("    public ").Append(sym.Name).AppendLine(" ToUnified() => new()");
        sb.AppendLine("    {");
        foreach (var f in fields)
        {
            var key = f.Type is IArrayTypeSymbol arr
                ? arr.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (packedNames.TryGetValue(key, out var winName))
            {
                if (f.Type is IArrayTypeSymbol)
                {
                    sb.Append("        ").Append(f.Name).Append(" = this.").Append(f.Name)
                      .Append(" is null ? null! : System.Array.ConvertAll(this.").Append(f.Name)
                      .Append(", static w => w.ToUnified()),");
                    sb.AppendLine();
                }
                else
                {
                    sb.Append("        ").Append(f.Name).Append(" = this.").Append(f.Name).AppendLine(".ToUnified(),");
                }
            }
            else
            {
                sb.Append("        ").Append(f.Name).Append(" = this.").Append(f.Name).AppendLine(",");
            }
        }
        sb.AppendLine("    };");
    }
}
