<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetPlatformIdentifier)' == 'windows'">
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>

</Project>
