using System.Security.Cryptography;
using KerckhoffsLabs.Runtime.InteropServices;
using KerckhoffsLabs.Security.Cryptography.Pkcs11.Common;
using KerckhoffsLabs.Security.Cryptography.Pkcs11.Native;
using KerckhoffsLabs.Security.Cryptography.Pkcs11.Native.RawMechanismParams;

namespace KerckhoffsLabs.Security.Cryptography.Pkcs11.Tests.Support.Pkcs11Fakes;

// RSA encryption / decryption: CKM_RSA_PKCS_OAEP (and the gated CKM_RSA_PKCS v1.5) over the live RSA
// key generated by C_GenerateKeyPair. Encrypt uses the public material, Decrypt the private — the
// same instance is indexed under both handles, so either resolves.
internal sealed partial class ManagedSoftToken
{
    private readonly Dictionary<ulong, (ulong key, RSAEncryptionPadding padding)> _rsaEncOps = [];

    private static bool IsRsaCipher(CKM m) => m is CKM.CKM_RSA_PKCS or CKM.CKM_RSA_PKCS_OAEP;

    private CKR InitRsaCipher(ulong session, ref CK_MECHANISM mech, ulong key)
    {
        if (!_sessions.Contains(session)) return CKR.CKR_SESSION_HANDLE_INVALID;
        if (!_asymKeys.TryGetValue(key, out var k) || k is not RSA) return CKR.CKR_KEY_HANDLE_INVALID;

        RSAEncryptionPadding padding = (CKM)(ulong)mech.Mechanism == CKM.CKM_RSA_PKCS
            ? RSAEncryptionPadding.Pkcs1
            : OaepPaddingFrom(ref mech);

        _rsaEncOps[session] = (key, padding);
        return CKR.CKR_OK;
    }

    private CKR RsaTransform(ulong session, ReadOnlySpan<byte> input, Span<byte> output, out NativeCULong outputLen, bool encrypt)
    {
        outputLen = (NativeCULong)0;
        if (!_rsaEncOps.TryGetValue(session, out var op)) return CKR.CKR_OPERATION_NOT_INITIALIZED;
        var rsa = (RSA)_asymKeys[op.key];

        byte[] result;
        try
        {
            byte[] data = input.ToArray();
            result = encrypt ? rsa.Encrypt(data, op.padding) : rsa.Decrypt(data, op.padding);
        }
        catch (CryptographicException)
        {
            _rsaEncOps.Remove(session);
            return encrypt ? CKR.CKR_DATA_LEN_RANGE : CKR.CKR_ENCRYPTED_DATA_INVALID;
        }

        if (output.IsEmpty) { outputLen = (NativeCULong)(ulong)result.Length; return CKR.CKR_OK; }
        if (output.Length < result.Length) { outputLen = (NativeCULong)(ulong)result.Length; return CKR.CKR_BUFFER_TOO_SMALL; }

        result.AsSpan(0, result.Length).CopyTo(output);
        outputLen = (NativeCULong)(ulong)result.Length;
        _rsaEncOps.Remove(session);
        return CKR.CKR_OK;
    }

    // CK_RSA_PKCS_OAEP_PARAMS.HashAlg selects the OAEP/MGF1 hash.
    private static RSAEncryptionPadding OaepPaddingFrom(ref CK_MECHANISM mech)
    {
        if (mech.Parameter == IntPtr.Zero) return RSAEncryptionPadding.OaepSHA1;

        var p = UnmanagedMemory.Read<CK_RSA_PKCS_OAEP_PARAMS>(mech.Parameter);
        return (CKM)(ulong)p.HashAlg switch
        {
            CKM.CKM_SHA_1 => RSAEncryptionPadding.OaepSHA1,
            CKM.CKM_SHA256 => RSAEncryptionPadding.OaepSHA256,
            CKM.CKM_SHA384 => RSAEncryptionPadding.OaepSHA384,
            CKM.CKM_SHA512 => RSAEncryptionPadding.OaepSHA512,
            var h => throw new CryptographicException($"ManagedSoftToken: unsupported OAEP hash {h}."),
        };
    }
}
